# Generated by Django 2.2.4 on 2019-08-21 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
    ]
